# Generated by Django 2.1.1 on 2019-02-01 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=256)),
                ('status', models.CharField(max_length=30)),
                ('duration', models.IntegerField()),
                ('submitter', models.CharField(max_length=30)),
            ],
        ),
    ]
