# Generated by Django 2.1.1 on 2019-02-03 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('regressions', '0002_auto_20190203_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='run',
            name='end',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='run',
            name='start',
            field=models.DateTimeField(null=True),
        ),
    ]
